version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: contatos-frontend-container
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules:ro
    command: npm start
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: contatos-backend-container
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production

  # jenkins:
  #   build: ./jenkins
  #   container_name: jenkins-container
  #   ports:
  #     - "8080:8080"      # Porta padrão do Jenkins
  #     - "50000:50000"    # Porta para comunicação com agentes do Jenkins
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock  # Jenkins acessa o Docker do host

# volumes:
#   jenkins-data: {}
